### ISSUE TITLE
reading led state and grab() ing device turns all leds off while retaining num/caps-lock state.

### ISSUE THREAD

**Issue by foxsam21** [gvalkov/python-evdev#107]
I asked this as a [question on stackoverflow](https://stackoverflow.com/questions/56316262/grab-after-device-leds-turns-off-led) but I think it may be a bug in the module itself.
If I read the led states and grab the device the leds turn off. It does not matter which one I do first. This is without pressing any keys (it's not a symptom of grab() not registering the release of numlock etc...). Even though the leds turn off the actual numlock state stays the same as it was. Another thing I noticed is that pressing one of caps/numlock restores the led state of both leds.
Here is an example:
```python
import evdev
evdev.InputDevice('/dev/input/event3').leds()
evdev.InputDevice('/dev/input/event3').grab()
```
If numlock led was on and capslock led off after running the above code both will be off. If i press numbers on the numberpad they work as if numlock is on even though the led is off. If I press capslock the capslock led will turn on and the numlock led will be restored to on.

**Comment by ssieb** [comment]
I can reproduce it with those lines, but why would you do that?  That code is useless.  If you create the device and then call grab() on it without discarding the object right away, the leds are not changed.  It has nothing to do with the preceding leds() call.

**Comment by foxsam21** [comment]
The reason I would do this is because I want to use a numeric keypad as a programmable keyboard and to have different functions for the num lock keys. Using the num lock led so I know which set of functions will be run would be nice if I can do it without changing the way the numeric keypad of my real keyboard works and returns to normal after. I also want the serrate numeric keypad to function normally when the progress is not running. 

I'm not sure what you mean. Without the LEDs call nothing is changed but with it the LEDs change. Why does it have nothing to do with it.
Thank you.

**Comment by ssieb** [comment]
Even if I don't run the line with the leds() call, the grab() will still turn off the LEDs.  It has no effect.

With further testing, I do see an issue.  The ungrab will turn off the LEDs, whether it's a direct call to ungrab() or from the device destructor.

**Comment by ssieb** [comment]
After much research and testing with a simple C program, it's definitely a kernel issue.  When a device is released, all handlers attached to the device get restarted.  My guess is that there is some handler that is resetting the LEDs.

**Comment by foxsam21** [comment]
Ok. Thanks for the effort. I am closing this because it's a kernel issue.

**Comment by atareao** [comment]
Thank you very much
