### ISSUE TITLE
Documentation Error: Tutorial Listing accessible event devices

### ISSUE THREAD

**Issue by windy54** [gvalkov/python-evdev#113]
I have just tried this tutorial on a raspberry PI running Buster, python 3.5.3 and it does not work.
```
import evdev
devices = [evdev.InputDevice(path) for path in evdev.list_devices()]
for device in devices:
	    print(device.path, device.name, device.phys)
```
Idle gives the following error:
	
Traceback (most recent call last):
  File "<pyshell#4>", line 2, in <module>
    print(device.path, device.name, device.phys)
AttributeError: "InputDevice" object has no attribute "path"

I have looked at help(evdev.device.InputDevice) and found an attribute __fspath__

If I now run
```
for device in devices:
	print(device.__fspath__, device.name, device.phys)
```

	
<bound method InputDevice.__fspath__ of InputDevice('/dev/input/event1')> Logitech USB Optical Mouse usb-3f980000.usb-1.5/input0
<bound method InputDevice.__fspath__ of InputDevice('/dev/input/event0')> DELL DELL USB Keyboard usb-3f980000.usb-1.4/input0

There are no errors and it outputs the path along with other information.

I am not sure if this is the "best" fix for the example, assuming there is an error. 

As a newcomer to evdev and relatively new to python I am quite pleased I managed to find a fix.

**Comment by ssieb** [comment]
What version of evdev do you have?  I have 1.1.2, but I also checked the latest code and "path" is definitely there.  Any attributes starting with ``__`` are internal only and in this case it's actually a method, not a string.  You're only seeing the path as a side effect of printing the device object.
Is this just Idle making a mistake or do you get that error if you run the script?

**Comment by windy54** [comment]
apologies for wasting your time, I thought I was using a PI with the very latest of everything, I was using an earlier version of stretch with version 0.8.1 of evdev!

I have upgraded to 1.2.0 and it works.

On a personal level I jave now learnt how to use pip3 freeze to check version numbers of python packages
