### ISSUE TITLE
module ‘evdev' has no attribute 'list_devices'

### ISSUE THREAD

**Issue by Zireael** [gvalkov/python-evdev#116]
Hi,
I'm trying to run example code from https://python-evdev.readthedocs.io/en/latest/usage.html on Ubuntu19 and getting an error that `module ‘evdev' has no attribute 'list_devices'`.
Relevant library versions are listed in the screenshot below.
```python
import evdev

devices = [evdev. InputDevice(path) for path in evdev.list_devices()]
for device in devices
print(device.path, device.name, device.phys)
```

![image](https://user-images.githubusercontent.com/3856578/71542267-33bd5e80-295c-11ea-8c55-6b99de1b22a4.png)

Any suggestion on what the issue could be?

**Comment by ssieb** [comment]
Your python script is called evdev.py, so it's importing itself.  That's why the stack trace is so strange.
