### ISSUE TITLE
Example for resolve_ecodes is missing one input parameter

### ISSUE THREAD

**Issue by Virusmater** [gvalkov/python-evdev#124]
I'm pretty new to python, so I don't feel like create pull request now since I'm not sure about it.
For resolve_ecodes:
def resolve_ecodes(ecode_dict, ecode_list, unknown='?'):
there is an example:
    >>> resolve_ecodes([272, 273, 274])
with only one input.
But I guess that it should have at least two.

**Comment by Virusmater** [comment]
can somebody confirm this? if so - will make a PR in a no time

**Comment by gvalkov** [comment]
Thanks for the catch. You are indeed right. I went ahead and fixed it in e0492245a3fed73cc586564e91ecd12421241274 .
