### ISSUE TITLE
ecodes.KEY doesn't return all items that ecodes.ecodes has

### ISSUE THREAD

**Issue by mad-ady** [gvalkov/python-evdev#133]
Hello,
I'm running evdev 1.3.0 on aarch64, python 3.7 (Debian 10.5). I've installed evdev from pip.
This is the problem I'm facing:
```
# python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from evdev import InputDevice, categorize, ecodes, UInput
>>> ecodes.ecodes['KEY_A']
30
>>> ecodes.KEY[30]
'KEY_A'
>>> ecodes.ecodes['BTN_DPAD_UP']
544
>>> ecodes.KEY[544]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 544
```

Any ideas why?

**Comment by ssieb** [comment]
It's not a key.
```
>>> ecodes.BTN[544]
'BTN_DPAD_UP'
```

**Comment by mad-ady** [comment]
Oh, thank you. I hadn't noticed BTN.
What's the preferred way of getting the name when you only have the key
code? Look it up in both KEY and BTN? Or is there a more generic way that
looks in both places?

Thanks

**Comment by ssieb** [comment]
Where are you getting the code from?  Isn't there some indication of the type in the event?

**Comment by mad-ady** [comment]
Hello,
In my case the driver reports the event type as ecodes.EV_KEY. There might
be a bug with the driver, in my case. Anyway, I'm looking for the key in
both places, in case it's not in KEY, no biggie.
Thanks!
