### ISSUE TITLE
Loop stuck, runs only once on each keypress

### ISSUE THREAD

**Issue by bskrt** [gvalkov/python-evdev#15]
I'm working on a project that needs to do certain things on specific keypresses.

To do this I'm using a loop to check the value of the pressed key and do something accordingly. The problem I'm having is that the while loop is interrupted whenever I'm using the getKey() function, so the rest of the loop only runs once after each keypress.

I'm probably doing something very basic horribly wrong as I've just started out with python recently. A push in the right direction would be of great help!

    from evdev import InputDevice, list_devices, categorize, ecodes

    dev = InputDevice('/dev/input/event0')
    def getKey():
        for event in dev.read_loop():
            if event.type == ecodes.EV_KEY:
                keybrd = categorize(event)
                if keybrd.keystate == keybrd.key_down:
                    c = keybrd.keycode
                    return c
                    c = ''

    while 42:
        c = getKey()
        print 'expected to be looping'
	
        if c == 'KEY_Z':
            print 'dosomething'
        if c == 'KEY_Q':
            print 'dosomethingelse'
        runSomeOtherFunctionThatNeedsToBeLooped()

**Comment by glaregoogle-fit-api** [comment]
https://pythoner.space/questions/pythons-conditional-loop-concept I recognized the response
