### ISSUE TITLE
creating a uinput device changes keymap

### ISSUE THREAD

**Issue by pfps** [gvalkov/python-evdev#168]
When I create a uinput device the keymap for my laptop keyboard changes.  I see this when running the following simple program

```
#!/usr/bin/env python3
import evdev
import time
fake = evdev.uinput.UInput()
time.sleep(5)
fake.close()
```

Here is what happens when I run the program:
```
idefix testing> setxkbmap -layout "us,us,us,us" -variant ",dvorak,colemak," -option grp:shifts_toggle
idefix testing> setxkbmap -query
rules:      evdev
model:      pc104
layout:     us,us,us,us
variant:    ,dvorak,colemak,
options:    grp:shifts_toggle
idefix testing> ./uinput.py 
idefix testing> setxkbmap -query
rules:      evdev
model:      pc104
layout:     us,us,us,us
variant:    ,intl,alt-intl,dvorak
```

Is the change to the keyboard mapping a desired change?  How can I not have this happen?

**Comment by sezanzeb** [comment]
> Is the change to the keyboard mapping a desired change?

This is controlled by your desktop environment. python-evdev can't do anything about this

> How can I not have this happen?

Unfortunately I don't know. Try wayland if you are on x11.

**Comment by pfps** [comment]
Thanks.
