### ISSUE TITLE
Instantiate UInput.from_device and add additional entries to capabilities

### ISSUE THREAD

**Issue by pastaq** [gvalkov/python-evdev#173]
I'm attempting to incorporate gyro controls into my virtual controller. I am able to create a UInput device and output EV_REL events from it. I want to add that functionality to the built-in controller on my device but I have been unable to find documentation on how to add new capabilities to an InputDevice or a UInput.from_device() after instantiating.

Things I have attempted:
- I instantiate xb360 in all versions via looping `list_devices()`, setting `xb360 = InputDevice(device.path)`
```py
ui = UInput.from_device(xb360, name="test-controller", version="0x3")
ui.capabilities().update({e.EV_REL: [e.REL_X, e.REL_Y, e.REL_Z, e.REL_RX, e.REL_RY, e.REL_RZ]})
```
- Doesn't change the output of `print(ui.capabilities())`

```py
cap = {e.EV_REL: [e.REL_X, e.REL_Y, e.REL_Z, e.REL_RX, e.REL_RY, e.REL_RZ]}
gyro = UInput(cap, name="test-gyro", version="0x3")
devices = [InputDevice(path) for path in list_devices()]
    for device in devices:
        if device.name == 'test-gyro':
            gyro_dev = InputDevice(device.path)

ui = UInput.from_device(xb360, gyro_dev, name="test-controller", version="0x3")
```
- gyro_dev is never found by list_devices() after instantiating and script fails.

Is it possible to add capabilities to an InputDevice after it has been instantiated? If so, how? If not, what am I missing in the second option that would have the UInput gyro discoverable via list_devices()?

**Comment by pastaq** [comment]
```
from evdev import InputDevice, UInput, ecodes as e, list_devices

keybd = None
caps = {e.EV_REL: [e.REL_X, e.REL_Y, e.REL_Z, e.REL_RX, e.REL_RY, e.REL_RZ]}
devices_orig = [InputDevice(path) for path in list_devices()]

for device in devices_orig:
    print(device.name)
    if device.name == 'AT Translated Set 2 keyboard':
        keybd = InputDevice(device.path)

# Uncomment only one to test
# Option 1
#ui = UInput.from_device(keybd, name='test-controller', version=0x3)
#print(ui.capabilities())
#ui.capabilities().update(caps)
#print(ui.capabilities())

#Option 2
gyro = None
gyro = UInput(caps, name='test-gyro', version = 0x3)
ui = UInput.from_device(keybd, gyro, name='test-controller', version=0x3)
print(ui.capabilities())
```

**Comment by pastaq** [comment]
I came up with a solution. I just need to manually build the capabilities dictionary. If I set a variable to .capabilities() I can then reference the capability in the assignment. i.e:

```
devices_orig = [InputDevice(path) for path in list_devices()]
    for device in devices_orig:
        if device.name == 'Microsoft X-Box 360 pad' and device.phys == 'usb-0000:03:00.3-4/input0':
            xb360 = InputDevice(device.path)
    
    xb_caps = xb360.capabilities()
    caps = {e.EV_ABS: xb_caps[e.EV_ABS],
            e.EV_FF: xb_caps[e.EV_FF],
            e.EV_KEY: xb_caps[e.EV_KEY],
            e.EV_REL: [e.REL_X, e.REL_Y, e.REL_Z, e.REL_RX, e.REL_RY, e.REL_RZ],
            }
    ui = UInput(caps, name="test", version=0x3)
```
This gives me all the same capabilities/characteristics and adds the new capability. I don't know how common this is, but I'd recommend adding an example of this into the docs somewhere.

**Comment by pastaq** [comment]
That's all sound advice, thank you.

**Comment by sezanzeb** [comment]
I think this can be closed, right?
