### ISSUE TITLE
Injecting events doesn't show output on the screen

### ISSUE THREAD

**Issue by testertesting322** [gvalkov/python-evdev#225]
I'm trying to follow the API example to write an A to the screen. 

How can I direct the output to a particular window/application?

 I tried sleeping and focusing on a text editor before the code execution below.

```
from evdev import UInput, ecodes as e
ui = UInput()
ui.write(e.EV_KEY, e.KEY_B, 1)  # KEY_A down
ui.write(e.EV_KEY, e.KEY_B, 0)  # KEY_A up
ui.syn()
ui.close()

```
I don't see any output on the screen.  
I can see that we are getting the key when I monitor with evtest:

> Select the device event number [0-18]: 18
> Input driver version is 1.0.1
> Input device ID: bus 0x3 vendor 0x1 product 0x1 version 0x1
> Input device name: "py-evdev-uinput"
> Supported events:
>   Event type 0 (EV_SYN)
>   Event type 1 (EV_KEY)
>     Event code 1 (KEY_ESC)
>     Event code 2 (KEY_1)
>     Event code 3 (KEY_2)
> ...
>  Event code 743 (BTN_TRIGGER_HAPPY40)
>   Event type 21 (EV_FF)
> Properties:
> Testing ... (interrupt to exit)
> Event: time 1733951067.135483, type 1 (EV_KEY), code 30 (KEY_A), value 1
> Event: time 1733951067.135483, type 1 (EV_KEY), code 30 (KEY_A), value 0
> Event: time 1733951067.135483, -------------- SYN_REPORT ------------

**Comment by ssieb** [comment]
You can't send it to a specific window.  This is the wrong level for that.  All that code does is pretend that the keyboard has typed a key.  Where that key goes is up to the window manager.

**Comment by sezanzeb** [comment]
Hm, I can't reproduce it unfortunately. It writes the letter "b" on my machine. I think I remember that in some cases, a bit of sleep between events can get things to work. Try something like

```py
from evdev import UInput, ecodes as e
import time

ui = UInput()

time.sleep(0.1)
ui.write(e.EV_KEY, e.KEY_B, 1)  # KEY_A down

time.sleep(0.1)
ui.write(e.EV_KEY, e.KEY_B, 0)  # KEY_A up

time.sleep(0.1)
ui.syn()

time.sleep(0.1)
ui.close()
```

Other than that, I don't know. Please share
- desktop environment
- distro
- X or Wayland?

> You can't send it to a specific window. This is the wrong level for that. All that code does is pretend that the keyboard has typed a key. Where that key goes is up to the window manager.

The point of focusing a window was probably just to test if the script above works. Which is a reasonable thing to do.

**Comment by sezanzeb** [comment]
> How can I direct the output to a particular window/application?

> You can't send it to a specific window. This is the wrong level for that. All that code does is pretend that the keyboard has typed a key. Where that key goes is up to the window manager.

Yes, what ssieb said is correct.

**Comment by oOosys** [comment]
I suggest to close or delete this issue, because it actually isn't an issue, but a question asking for help on understanding the by the module provided functionality.
