### ISSUE TITLE
Error in util.py

### ISSUE THREAD

**Issue by tobiz** [gvalkov/python-evdev#27]
line 14 on util.py reads:
```
fns = glob.glob('{}/event*'.format(input_device_dir))
```

to work (on python 2.6) it has to read:
```
fns = glob.glob('{0}/event*'.format(input_device_dir))
```

If you run the first tutorial example with the current util.py line 14 you get:
```
>>> devices = map(InputDevice, list_devices())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/evdev/util.py", line 14, in list_devices
    fns = glob.glob('{}/event*'.format(input_device_dir))
ValueError: zero length field name in format
```

If you run the modified line 14 you get:
```
>>> fns = glob.glob('{0}/event*'.format('/dev/input'))
>>> print fns
['/dev/input/event6', '/dev/input/event5', '/dev/input/event4', '/dev/input/event3', '/dev/input/event2', '/dev/input/event1', '/dev/input/event0']
```

Hope that helps

**Comment by gvalkov** [comment]
Hello @tobiz. I appreciate the effort, but supporting Python 2.6 is not something I'm looking into. By requiring 2.7 as the minimum supported version, we basically get `>=3.3` support for free with a single codebase. Adding 2.6 to the mix would complicate the py3k support.
