### ISSUE TITLE
Error in device.py

### ISSUE THREAD

**Issue by tobiz** [gvalkov/python-evdev#28]
Line 217 should be (under python 2.6):
        return '{0!r}'.format(msg)
Not:
        return '{}({!r})'.format(msg)
Is this valid syntax anyway, use of (), since {0}({!r}) doesn't work!

Having made my changes tutorial 1 now works under python 2.6

**Comment by gvalkov** [comment]
Hello @tobiz and sorry for the late reply. I'm afraid that the lowest Python version that this project supports is 2.7. I sincerely hope you're able to migrate away from Python 2.6.
