### ISSUE TITLE
Problem with the tutorial code for "Specifying uinput device options"

### ISSUE THREAD

**Issue by albertotonda** [gvalkov/python-evdev#30]
First of all, thanks for your great work! :-)

Using the code provided in "Specifying uinput device options" raises an error (using Python2.7, python-evdev 0.4.5, Ubuntu 14.04) :

```
cap = { ecodes.EV_KEY : [ecodes.KEY_A, ecodes.KEY_B], ecodes.EV_ABS : [ (ecodes.ABS_X, AbsInfo(min=0, max=255, fuzz=0, flat=0)), (ecodes.ABS_Y, AbsInfo(0, 255, 0, 0)), (ecodes.ABS_MT_POSITION_X, (0, 255, 128, 0)) ] }
TypeError: __new__() takes exactly 7 arguments (5 given)
```

Probably because the constructor of AbsInfo changed somehow? I can see how a new parameter called "resolution" has been added, but I don't understand what is the 7th argument. Correcting the AbsInfo instances with:

```
AbsInfo(min=0, max=255, fuzz=0, flat=0, resolution=0)
```

raises the same error

```
TypeError: __new__() takes exactly 7 arguments (6 given)
```

Changing the line to:

```
AbsInfo(0, 255, 0, 0, 0, 0)
```

executes without errors, but (and this might be a separate issue) the virtual mouse does not move, albeit the EV_KEY events work.

**Comment by nadrimajstor** [comment]
My issue is probably related to the one OP has. On my Ubuntu 14.04.2 I had to explicitly put at minimum this two capabilities:

```python
capabilities = {
    evdev.ecodes.EV_REL: (evdev.ecodes.REL_X, evdev.ecodes.REL_Y),
    evdev.ecodes.EV_KEY: (evdev.ecodes.BTN_LEFT, evdev.ecodes.BTN_RIGHT)
    }
```
Omitting any of those will end up with a state where `py-evdev-uinput` is not registered in the `Virtual core pointer` list (as shown by the `xinput` command). 

@gvalkov Thank you for this great tool. My Wacom tablet finally behaves "Just the way I like it" :tm:
