### ISSUE TITLE
Installing python-evdev on arduino yun - fhonour-copts error

### ISSUE THREAD

**Issue by VictorAtreides** [gvalkov/python-evdev#34]
Hi:
I am trying to install python-evdev on my arduino yun using  "./setup.py install". I get the following error: Any suggestion will be appreciated (bear in mind that I am a newbie).

```
./setup.py install

running install

running bdist_egg

writing ecodes.c (using /usr/include/linux/input.h)

running egg_info

writing evdev.egg-info/PKG-INFO

writing top-level names to evdev.egg-info/top_level.txt

writing dependency_links to evdev.egg-info/dependency_links.txt

reading manifest file 'evdev.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'evdev.egg-info/SOURCES.txt'

installing library code to build/bdist.linux-mips/egg

running install_lib

running build_py

running build_ext

building 'evdev._input' extension

mips-openwrt-linux-uclibc-gcc -fno-strict-aliasing -Os -pipe -mips32r2 
-mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -DNDEBUG -Os -pipe -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -fPIC -I/usr/include/python2.7 -c evdev/input.c -o build/temp.linux-mips-2.7/evdev/input.o -std=c99 -Wno-error=declaration-after-statement

cc1: error: unrecognized command line option '-fhonour-copts'

cc1: error: unrecognized command line option '-fhonour-copts'

error: command 'mips-openwrt-linux-uclibc-gcc' failed with exit status 1

root@Arduino:/mnt/sda1/python-evdev-0.4.7# cc1: error: unrecognized command 
line option '-fhonour-copts'
-ash: cc1:: not found
root@Arduino:/mnt/sda1/python-evdev-0.4.7# cc1: error: unrecognized command line option '-fhonour-copts'
-ash: cc1:: not found
```

**Comment by gvalkov** [comment]
Hello @VictorAtreides,

A few months ago another person was also interested in building python-evdev on the Arduino Yun. I made an ipkg file (a package which you can install using openwrt's package manager - opkg)  for him and also submitted it for inclusion in the Arduino Yun [package tree](https://github.com/arduino/openwrt-packages-yun/pull/25). [Here](http://stackoverflow.com/questions/27868339/python-evdev-binding-for-openwrt) is his StackOverflow question for reference.

You could try downloading the prebuilt package from [here](https://www.dropbox.com/s/ce44jh9udlubq01/python-evdev_0.4.7-1_ar71xx.ipk?dl=0)  (sorry, sharing it on dropbox is all I could think of at the moment) and installing with:

```bash
$ opkg update
$ opkg install /path/to/python-evdev_0.4.7-1_ar71xx.ipk
```

Please let me know if this works for you. If not, we could troubleshoot the compilation issue more thoroughly.

Best regards,
Georgi

**Comment by VictorAtreides** [comment]
Hi Gregory:

I was able to install the ev-dev package on my YUN!! Thanks a lot for your valuable contribution.
Best regards!
Victor
________________________________

**Comment by LSChyi** [comment]
Hello @gvalkov, recently there is a new board called Linkit smart 7688, which is a cheap IoT board. I was trying to use this board to build an bluetooth keyboard adapter, and just like Arduino Yun, it uses openwort as the OS.
As I was trying to use this awesome plugin, the installation was failed due to miss linux kernel header files. Then I found there is another evdev for Arduino Yun, I downloaded and run opkg install to install that package, it popped error messages, saying that "incompatible with the architectures configured".
Can you give some advises? Thank you!

spec of Linkit smart 7688:
MIPS CPU
