### ISSUE TITLE
Send vibration to gamepad

### ISSUE THREAD

**Issue by kharlashkin** [gvalkov/python-evdev#38]
Hi!
I'm try send vibration to Xbox 360 controller with python. Do you have example of sending vibroeffect with evdev?

**Comment by mncharity** [comment]
#23 may be related.

**Comment by kharlashkin** [comment]
Thanks, I necessarily try new code in my priject.

**Comment by gvalkov** [comment]
This should now be possible - have a look at the [examples in the documentation](https://python-evdev.readthedocs.io/en/latest/tutorial.html#create-uinput-device-capable-of-recieving-ff-effects).
