### ISSUE TITLE
Import error with Linux kernel 4.4.0

### ISSUE THREAD

**Issue by arcriley** [gvalkov/python-evdev#43]
Using Gentoo's gentoo-sources-4.4.0, python-evdev generates from a input.h which causes it to fail on input:
# python

Python 2.7.11 (default, Jan 21 2016, 21:00:40) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from evdev import UInput, UInputError, ecodes
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib64/python2.7/site-packages/evdev/**init**.py", line 5, in <module>
> > >     from evdev.device import DeviceInfo, InputDevice, AbsInfo
> > >   File "/usr/lib64/python2.7/site-packages/evdev/device.py", line 7, in <module>
> > >     from evdev import _input, _uinput, ecodes, util
> > >   File "/usr/lib64/python2.7/site-packages/evdev/ecodes.py", line 75, in <module>
> > >     keys.update(BTN)
> > > NameError: name 'BTN' is not defined

This affects at least python-evdev 0.4.5 and 0.5.0 and can be fixed by downgrading both the kernel and sys-kernel/linux-headers to version 4.3, then rebuilding python-evdev.

**Comment by gvalkov** [comment]
Thank you for reporting this. The issue seems to be related to this change: https://github.com/torvalds/linux/commit/f902dd893427eade90f7eaf858e5ff8b150a5a12. Commit 631e2d32d7bdf38e3d7a5c850c9f5869d61e9183 should take care of it.

I would appreciate it if you could verify this fix with:
```
pip install --upgrade git+https://github.com/gvalkov/python-evdev.git@631e2d32d7bdf38e3d7a5c850c9f5869d61e9183
```

**Comment by pztrick** [comment]
@gvalkov Also encountered his `BTN` exception on old project pinned to `evdev==0.5.0`. 

Both the referenced commit and upgrading to `evdev==0.6.0` resolved this issue so you can probably close. :+1:

**Comment by rasendubi** [comment]
I also confirm that updating evdev helps.

@gvalkov, should this be closed?

**Comment by gvalkov** [comment]
Thanks for verifying :+1:
