### ISSUE TITLE
Add a description of what is/not working

### ISSUE THREAD

**Issue by mncharity** [gvalkov/python-evdev#57]
Some uses of uinput are not currently supported (for example, rumblers: #23, [ff branch](/gvalkov/python-evdev/tree/ff)).  Which, doesn't seem to be documented.

Adding to the documentation, a brief description of what is and isn't working, might help potential users anticipate whether python-evdev is appropriate for their intended use.

Here is a strawman draft:
## Scope and status

All keyboard and mice events should work.  Rumblers #23 currently do not work.  Joysticks, touchpads, tablets, cameras, force feedback, and less common devices _probably work / probably don't work / sometimes work / partially work / haven't been tested / are not supported_.

Some characters, such as `:` (colon), cannot easily be generated from scratch #7.  Translating them into UInput events would require knowing the kernel keyboard translation table, and there is no python equivalent of `dumpkeys`.  Consider using [PyUserInput](https://github.com/PyUserInput/PyUserInput) instead.

Related projects include: [python-uinput](https://pypi.python.org/pypi/python-uinput/); [uinput-mapper](https://github.com/MerlijnWajer/uinput-mapper); [PyUserInput](https://github.com/PyUserInput/PyUserInput); [pygame](http://www.pygame.org/).

**Comment by gvalkov** [comment]
Hello @mncharity and apologies for replying with such great delay. I added a short paragraph on the subject in 84f6b03c11d5aaee4eff42b4fb439cd7993abf48.
