### ISSUE TITLE
Pointer does not move with ecodes.EV_REL

### ISSUE THREAD

**Issue by om26er** [gvalkov/python-evdev#61]
I am trying to move the mouse visually on screen for an automation tool that I am working on, it seems the mouse pointer does not move with ecodes.EV_REL. I am working on Ubuntu and I tried on both X11 and Mir display server. python-uinput seems to be working fine though, but our project heavily uses python-evdev so we need to keep using it. Below is the code that reproduces the issue.

```
from time import sleep

from evdev import UInput, ecodes

ui = UInput()
for i in range(20):
    ui.write(ecodes.EV_REL, ecodes.REL_X, 5)
    ui.write(ecodes.EV_REL, ecodes.REL_Y, 5)
    ui.syn()
    sleep(0.01)
```

That codes does run without errors but it does not do anything, OTH, mouse click events do work.

**Comment by paulo-raca** [comment]
AFAICT, you must set your device's capabilities so that it "looks like a mouse", and your display server will handle it accordingly.

Try this:

```
ui = UInput({
    ecodes.EV_REL: [ecodes.REL_X, ecodes.REL_Y],
    ecodes.EV_KEY: [ecodes.BTN_LEFT],
})
```

**Comment by om26er** [comment]
That worked. Thanks a lot.

**Comment by gvalkov** [comment]
Thank you for @paulo-raca for assisting @om26er with this. I will look into improving the documentation, as this is one of the most common issues people face with the uinput functionality.
