### ISSUE TITLE
After update 0.6.3 error installing on Raspbian Jessie

### ISSUE THREAD

**Issue by meguia** [gvalkov/python-evdev#63]
Using updated Raspbian Jessie with all the dependencies installed, now when I try to install with pip (or pip3)
`sudo pip install evdev`
Then when building 'evdev._ecodes' extension I get the following error:
`In file included from /usr/include/python2.7/Python.h:126:0,
                     from evdev/ecodes.c:2:
    evdev/ecodes.c: In function ‘moduleinit’:
    evdev/ecodes.c:69:29: error: ‘BUS_RMI’ undeclared (first use in this function)
         PyModule_AddIntMacro(m, BUS_RMI);`

Thanks in advance!

**Comment by gvalkov** [comment]
Hi and thank you for reporting this :+1:  

I just pushed 0.6.4 with a [fix](9219ef10788d9136edf395bc77ed15662b7e484c) for this. I had failed to account for an interaction between the `build_ecodes` command introduced in 0.6.3 and the fact that `ecodes.c` was part of the source distribution. Long story short, the `ecodes.c` source file was not being re-generated at install time and the bundled one was built against a kernel version newer than the one in raspbian jessie.
