### ISSUE TITLE
'Invalid Argument' error when trying to create a UInput with EV_FF

### ISSUE THREAD

**Issue by quinnyo** [gvalkov/python-evdev#76]
Unable to create a UInput device from an xbox 360 controller due to the EV_FF capability.
Similar to #60 but the EV_FF capability needs to be filtered out as well as EV_SYN

**Comment by gvalkov** [comment]
Thanks for the bug report and sorry for the month-long delay. `EV_FF` is now filtered in fd0ecf21772f37b06be1c702cca79eb285136b3d.
