### ISSUE TITLE
UInput.from_device does not merge every event code

### ISSUE THREAD

**Issue by ismailof** [gvalkov/python-evdev#77]
When using `UInput.from_device()` to merge the capabilities of several devices, the resulting capabilities of the uinput device are not the full list of those in the source devices.

Since for each ev_type in `dev.capabilities()` we have a list of ev_codes, if two devices have same ev_type but differente ev_codes, the update method on `uinput.py` replaces the previous list with the last ones:
```
     all_capabilities = {}
     for dev in device_instances:
         all_capabilities.update(dev.capabilities())
```

To correctly merge capabilities of several devices we should do something like this to extend the lists instead of replacing them:
```  
    all_capabilities = defaultdict(list)
    for dev in device_instances:
        dev_caps = dev.capabilities()        
        for ev_type, ev_codes in dev_caps.iteritems():
            all_capabilities[ev_type].extend(ev_codes)
            all_capabilities[ev_type] = list(set(all_capabilities[ev_type]))  # removes duplicate ev_codes
```  

The last line could be avoided if instead of lists we had sets for device capabilities, which would automatically avoid duplicate ev_codes, but that might be a bigger API change, I think.

I could do a pull request if you find it appropriate

**Comment by gvalkov** [comment]
Thanks for the bug report and fix! I simplified it a bit further, like so:

```python
all_capabilities = defaultdict(set)

for dev in device_instances:
    for ev_type, ev_codes in dev.capabilities().items():
        all_capabilities[ev_type].update(ev_codes)
```
