### ISSUE TITLE
changing fd

### ISSUE THREAD

**Issue by mrmsbarnes** [gvalkov/python-evdev#78]
import evdev
devices = (evdev.InputDevice('/dev/input/event1'), evdev.InputDevice('/dev/input/event2'))
for dev in devices:
    print (dev.fd, dev)
print (evdev.InputDevice('/dev/input/event1').fd, evdev.InputDevice('/dev/input/event1'))
print (evdev.InputDevice('/dev/input/event2').fd, evdev.InputDevice('/dev/input/event2'))

output:
pi@raspberrypi:~ $ python3 mhook2.py
3 device /dev/input/event1, name "Rextron USB", phys "usb-3f980000.usb-1.3.1/input1"
4 device /dev/input/event2, name "lircd-uinput", phys ""
5 device /dev/input/event1, name "Rextron USB", phys "usb-3f980000.usb-1.3.1/input1"
5 device /dev/input/event2, name "lircd-uinput", phys ""

why do fd's change from 3 and 4 to 5?

**Comment by paulo-raca** [comment]
Every time you create a new `evdev.InputDevice()`, you are creating a brand-new communication channel with the device, and each one of those happen over a distinct fd:

- The fds 0, 1 and 2 are usually taken for stdin/stdout/stderr

- The instance in `devices` are assigned the fds 3 and 4.

Once the `InputDevice` is no longer used, the fd is released and the same number can reused later on. on the last 2 lines, you are creating and discarding 4 instances of `InputDevice`. Each one of these take the fd 5 and release it soon after.

Now that you know what is happening, you probably want to stick to a single `InputDevice` instance ;)

**Comment by mrmsbarnes** [comment]
Many thanks.
