### ISSUE TITLE
Syntax Error in 0.8.0

### ISSUE THREAD

**Issue by joh06937** [gvalkov/python-evdev#83]
...
    import evdev
  File ".../python2.7/site-packages/evdev/__init__.py", line 9, in <module>
    from evdev.uinput import UInput, UInputError
  File ".../python2.7/site-packages/evdev/uinput.py", line 35
    def from_device(cls, *devices, filtered_types=(ecodes.EV_SYN, ecodes.EV_FF), **kwargs):
                                                ^
SyntaxError: invalid syntax

**Comment by gvalkov** [comment]
Thanks for the catch. It's fixed in evdev 0.8.1. I've gotten really used to the niceties of Python 3.

**Comment by joh06937** [comment]
No problem. One of these days I'll get my company off of Python 2.7...
