### ISSUE TITLE
How to read events using asyncio

### ISSUE THREAD

**Issue by MouhamedEssam** [gvalkov/python-evdev#85]
in the documentation, there is an example to read events using asyncore with a note along the example suggesting to use asyncio with no explanation, and am also need explanation what is the need of reading events using asyncore.

**Comment by tacaswell** [comment]
There is also an example just further down the page.

https://python-evdev.readthedocs.io/en/latest/tutorial.html#reading-events-from-multiple-devices-using-asyncio
