### ISSUE TITLE
AttributeError: 'InputDevice' object has no attribute 'path' when comparing equality

### ISSUE THREAD

**Issue by siikamiika** [gvalkov/python-evdev#90]
The `path` attribute added in 711606f4a7e41a967c763e03fada9f6046b38f09 doesn't work for me on CPython 3.6.4. I was comparing two references to the same object, and the actual device behind `InputDevice` did not exist at that moment (it was unplugged). I'd send a pull request undoing the commit but I don't know if that would break something else.

**Comment by gvalkov** [comment]
Hi. I don't know what I was thinking when I was implementing ... there really is no `path` attribute in `InputDevice`. This was taken care of in 254d945451991deb33976d3bca68a54bdde88702. I'll be releasing a new version soon - thanks for the catch :+1:

**Comment by siikamiika** [comment]
Ah, it's going to change from `fn` to `path`. I'll be sure to replace the occurrences of `fn` in my code when I update python-evdev. Thanks!
