### ISSUE TITLE
"name 'buffer' is not defined" when calling upload_effect

### ISSUE THREAD

**Issue by robomancer-or** [gvalkov/python-evdev#95]
When I call upload_effect to get force feedback working it's throwing an error because it can't find `buffer`.

I've tracked it to line 293 of https://github.com/gvalkov/python-evdev/blob/ff/evdev/device.py apparently the function buffer is nowhere to be found...??

**Comment by gvalkov** [comment]
This was apparently fixed in 3fd0bb945332c74e1c6a20590319f96be788a0c9. Feel free to upgrade to 1.0.0 - it should fix the problem.
