### ISSUE TITLE
Bug: min/max 0 (becuase absinfo is empty on 1.1.0)

### ISSUE THREAD

**Issue by c-andy-martin** [gvalkov/python-evdev#97]
I believe this change broke absinfo on object creation:

https://github.com/gvalkov/python-evdev/commit/34fe42c0b5bf015b4b8315833b19d32d0b4de440

It calls _uinput.setup passing `absinfo` before `absinfo` was setup using the passed in `events` dictionary. This causes invalid behavior, for instance, w/ ds4drv:

Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x54c product 0x5c4 version 0x111
Input device name: "Sony Computer Entertainment Wireless Controller"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 304 (BTN_SOUTH)
    Event code 305 (BTN_EAST)
    Event code 306 (BTN_C)
    Event code 307 (BTN_NORTH)
    Event code 308 (BTN_WEST)
    Event code 309 (BTN_Z)
    Event code 310 (BTN_TL)
    Event code 311 (BTN_TR)
    Event code 312 (BTN_TL2)
    Event code 313 (BTN_TR2)
    Event code 314 (BTN_SELECT)
    Event code 315 (BTN_START)
    Event code 316 (BTN_MODE)
    Event code 317 (BTN_THUMBL)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    124
      Min        0
      Max        0
    Event code 1 (ABS_Y)
      Value    128
      Min        0
      Max        0
    Event code 2 (ABS_Z)
      Value    129
      Min        0
      Max        0
...

And so on (all min/max values are 0!)

**Comment by gvalkov** [comment]
Fixed in a920153ba5b71b8393526a7aa40d9fb717371618 and available in evdev 1.1.1. Thanks for the catch!
