### ISSUE TITLE
Dynamically update device list using asyncio

### ISSUE THREAD

**Issue by fenhl** [gvalkov/python-evdev#99]
I'm using this library's `asyncio` API to listen for events from all devices. The issue I'm having is that the list of available devices needs to be created in advance, so new devices plugged in while my program is already running are ignored, and even worse, unplugging a device crashes my program with an `OSError`.

It would be useful if this library could provide a solution, perhaps in form of an async iterator which simply yields events from all devices, along with the device that generated them. For additional information parity, special “device added/removed” events could be inserted as well.

Tagging @paulo-raca — maybe you have an idea of how to implement this, since it looks like you added the `asyncio` support to this library.

**Comment by gvalkov** [comment]
Hi @fenhl, @paulo-raca, 

This is possible using [pyudev](https://pyudev.readthedocs.io/en/latest/) - there's already [an example](https://github.com/gvalkov/python-evdev/blob/master/examples/udev-example.py) that shows how to use `evdev` and `pyudev`. 

An asyncio API on top of these would be quite nice, but I can't think of a good API at the moment. I'll leave this issue open, since it would definitely be nice to have.

**Comment by wazari972** [comment]
Hello,

if anyone needs a solution, it can work this way:
```python
def handle_new_devices(loop):
    class EventHandler(pyinotify.ProcessEvent):
        def process_IN_CREATE(self, event):
            if event.dir: return
            if not event.name.startswith("event"): return
            dev = evdev.InputDevice(event.pathname)
            print(f"{dev} CONNECTED")

    wm = pyinotify.WatchManager()  # Watch Manager
    mask = pyinotify.IN_CREATE  # watched events

    notifier = pyinotify.AsyncioNotifier(wm, loop, default_proc_fun=EventHandler())
    wm.add_watch('/dev/input', mask, rec=True, auto_add=True)
    return notifier

loop = asyncio.get_event_loop()
notifier = handle_new_devices(loop)
...
notifier.stop()
```

**Comment by fenhl** [comment]
Unfortunately, this code also crashes when a device is unplugged.

**Comment by wazari972** [comment]
strange, I'm using it since I posted it last time, do you have the stack or any information about the crash ?

**Comment by gvalkov** [comment]
Hi @fenhl . A request for something like this comes in every now and then. It's really not in the scope of this project, but I've put together an example of how to use [pyudev](https://pyudev.readthedocs.io/en/latest/) alongside evdev: see  [examples/udev-example.py](https://github.com/gvalkov/python-evdev/blob/master/examples/udev-example.py)
